services:
  backend-api:
    image: ${BACKEND_API_IMAGE}:${BACKEND_API_IMAGE_TAG}
    environment:
      NODE_ENV: production
      PORT: 3000
      GRAPHQL_PATH: /graphql
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: unless-stopped
    networks:
      - platform-net

  scraper-service:
    image: ${SCRAPER_SERVICE_IMAGE}:${SCRAPER_SERVICE_IMAGE_TAG}
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      REDIS_URL: redis://redis:6379
      QUEUE_RAW_EVENT: source.raw.v1
      SCRAPE_SCHEDULE: "*/20 * * * *"
      USE_PLAYWRIGHT: "false"
      SHARED_CONTRACTS_DIR: /opt/shared-contracts
      S3_ENDPOINT: http://minio:9000
      S3_REGION: ru-central-1
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET: ${MINIO_BUCKET}
    volumes:
      - ./contracts:/opt/shared-contracts:ro
    depends_on:
      - rabbitmq
      - minio
    restart: unless-stopped
    networks:
      - platform-net

  processing-worker:
    image: ${PROCESSING_WORKER_IMAGE}:${PROCESSING_WORKER_IMAGE_TAG}
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      REDIS_URL: redis://redis:6379
      API_GRAPHQL_URL: http://backend-api:3000/graphql
      QUEUE_RAW_EVENT: source.raw.v1
      QUEUE_NORMALIZED_EVENT: source.normalized.v1
      SHARED_CONTRACTS_DIR: /opt/shared-contracts
    volumes:
      - ./contracts:/opt/shared-contracts:ro
    depends_on:
      - rabbitmq
      - backend-api
    restart: unless-stopped
    networks:
      - platform-net

  frontend-app:
    image: ${FRONTEND_APP_IMAGE}:${FRONTEND_APP_IMAGE_TAG}
    ports:
      - "8080:80"
    depends_on:
      - backend-api
    restart: unless-stopped
    networks:
      - platform-net

networks:
  platform-net: {}
